### PR TITLE
Update _start_game and _end_game

### PR DESCRIPTION
**Pull request by TongTszHo**
(https://github.com/Kush-Gold-Rush/MineShaft/issues/9)

 Find and start the game 

And end the game

### CODE REVIEW

**Review by NewJerseyStyle — CHANGES_REQUESTED** [review]
A very good idea to use `subprocess`

But I don't see why both `lnk` and `exe` are used. Can you explain a little more about it?

And import here is not good. You may ask Sharon, she did good on `import` things.

**Comment by NewJerseyStyle** [comment]
Sure you did try to run this function on your computer? I will try to run it tonight then.

**Review by NewJerseyStyle — CHANGES_REQUESTED** [review]
Good. Almost there. One last thing: Do not use global variable.

**Comment by TongTszHo** [comment]
I have correct to not use global variables, and success to run

**Review by NewJerseyStyle — APPROVED** [review]

**Comment by NewJerseyStyle** [comment]
Docstring not good, I will ask Sharon to help on that. And can you check if the `subprocess` implementation can still apply the `try/catch` in `__init__` for the error if game not installed?

**Pull request merged**
